GREMLIN_HOST: '192.168.0.143'  #private ip (get by running `hostname -I`)
GREMLIN_PORT: 8182

HISTORICAL_EVALUATIONS_FROM: '2021-06-22'
HISTORICAL_EVALUATIONS_DURATION_STEPS: 10
HISTORICAL_EVALUATIONS_STEP_DAYS: 5
