GREMLIN_HOST: '192.168.0.143'  #private ip (get by running `hostname -I`)
GREMLIN_PORT: 8182

MYSQL_HOST: '192.168.0.143'
MYSQL_PORT: 3306
MYSQL_USER: 'root'
MYSQL_PASSWORD: 'pwd'
MYSQL_DATABASE: 'db'
